import type { SanityAsset } from "@sanity/image-url/lib/types/types";

// Generated by https://quicktype.io
export interface Post {
  slug: Slug;
  publishedAt: string;
  title: string;
  excerpt: string;
  _rev: string;
  mainImage: MainImage;
  _createdAt: string;
  _id: string;
  _updatedAt: string;
  author: Author;
  _type: string;
  categories: Category[];
  body: Body[];
}

export interface Author {
  name: string;
  role: string;
  image: Image;
}

export interface Image {
  hotspot: Hotspot;
  _type: string;
  asset: SanityAsset;
  crop: Crop;
}

export interface Crop {
  top: number;
  left: number;
  bottom: number;
  _type: string;
  right: number;
}

export interface Hotspot {
  x: number;
  y: number;
  height: number;
  _type: string;
  width: number;
}

export interface Body {
  style: Style;
  _key: string;
  markDefs: MarkDef[];
  children: Child[];
  _type: BodyType;
  image: null;
  listItem?: ListItem;
  level?: number;
}

export enum BodyType {
  Block = "block",
}

export interface Child {
  _type: ChildType;
  marks: Key[];
  text: string;
  _key: string;
}

export enum ChildType {
  Span = "span",
}

export enum Key {
  Cd1Cface4273 = "cd1cface4273",
  Strong = "strong",
  The43134035C8B1 = "43134035c8b1",
}

export enum ListItem {
  Bullet = "bullet",
}

export interface MarkDef {
  _type: string;
  href: string;
  _key: Key;
}

export enum Style {
  H2 = "h2",
  Normal = "normal",
}

export interface Category {
  title: string;
}

export interface MainImage {
  _type: string;
  asset: Asset;
}

export interface Slug {
  current: string;
  _type: string;
}
